name: release-automation

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
        matrix:
            node: [14]
            platform: [windows, linux]
            os: [windows-latest, ubuntu-latest]
            target: [deb, msi]
            bundler: [tauri, electron]
            design-system: [win98, spectre, nes]
            exclude:
                - platform: windows
                  os: ubuntu-latest
                - platform: linux
                  os: windows-latest
                - platform: window
                  target: deb
                - platform: linux
                  target: msi
                - bundler: tauri
                - platform: windows

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: update npm
        run: npm install -g npm@latest

      - name: install Rust stable
        if: ${{ matrix.bundler == 'tauri' }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: install node_modules
        working-directory: src
        run: npm install

      - name: build
        working-directory: src
        run: ./scripts/build.sh -v -p ${{ matrix.platform }} -b ${{ matrix.bundler }} -d ${{ matrix.design-system }}

      - name: Upload installer.
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.platform }}-${{ matrix.bundler }}-${{ matrix.design-system }}
          path: src/dport.${{ matrix.target }}

  do-release:
    needs:
      - build

    runs-on: ubuntu-latest

    steps:
      - name: Download linux-electron-win98
        uses: actions/download-artifact@v1
        with:
          name: linux-electron-win98

      - name: Download linux-electron-spectre
        uses: actions/download-artifact@v1
        with:
          name: linux-electron-spectre

      - name: Download linux-electron-nes
        uses: actions/download-artifact@v1
        with:
          name: linux-electron-nes

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload linux-electron-win98
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: linux-electron-win98/dport.deb
          asset_name: dport-electron-win98-${{ github.ref }}.deb
          asset_content_type: application/octet-stream

      - name: Upload linux-electron-spectre
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: linux-electron-spectre/dport.deb
          asset_name: dport-electron-spectre-${{ github.ref }}.deb
          asset_content_type: application/octet-stream

      - name: Upload linux-electron-nes
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: linux-electron-nes/dport.deb
          asset_name: dport-electron-nes-${{ github.ref }}.deb
          asset_content_type: application/octet-stream
