name: test
on: [push]

jobs:
  test-linux-tauri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - working-directory: docker
        run: make tauri-base
      - working-directory: docker
        run: make tauri-test

  test-linux-electron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - working-directory: docker
        run: make electron-base
      - working-directory: docker
        run: make electron-test
